name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build, test, and push
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sign into Docker Hub
        run: |
          docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_TOKEN"
      - name: Install Earthly
        run: |
          wget https://github.com/earthly/earthly/releases/download/v0.6.29/earthly-linux-amd64 -O /usr/local/bin/earthly
          chmod +x /usr/local/bin/earthly
      - name: Verify Earthly works
        run: earthly --version
      - name: Run tests
        run: earthly --ci +test
      - name: Run linter
        run: earthly --ci +lint
      - name: Push images
        run: earthly --ci --push +image
        if: startsWith(github.ref, 'refs/tags/v')
